server:
  port: 8080

spring:
  jpa:
    # Prints current SQL query executed. Used for debug purposes.
    show-sql: false
    # Database type is SQLite
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      # Avoid creating stuff automatically
      ddl-auto: none
    properties:
      hibernate:
        # Pretty print all SQL queries in console
        format_sql: true
  datasource:
    # Property to specify the location of the main SQLite database
    url: jdbc:sqlite:database.db
    # Database driver
    driver-class-name: org.sqlite.JDBC
  mustache:
    check-template-location: false
  threads:
    virtual:
      enabled: true

logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    # Property for defining root level for application logs.
    root: INFO # use DEBUG as a value for activating DEBUG level
    # Uncomment the following property if you want to activate debug level only for classes created by this app.
    #org:
    #  myalerts: DEBUG
  logback:
    rollingpolicy:
      max-file-size: 100MB # Limit for log file size
      max-history: 10 # Activate log rolling
  file:
    name: application.log # Default name for a logging file

my-alerts:
  config:
    library:
      base-directory: "libs"
