server:
  port: 8000

spring:
  jpa:
    database-platform: org.myalerts.app.dialect.SQLiteDialect
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:sqlite:database.db
    driver-class-name: org.sqlite.JDBC
  mustache:
    check-template-location: false

settings:
  test-scenario-scheduler:
    pool-size: 2
    thread-name-prefix: "test-scenario-pool-"
